# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
laser_scan_layer:
  enabled: true
  obstacle_range: 10.5
  raytrace_range: 10.5
  inflation_radius: 1.2
  combination_method: 1
  observation_sources: 2d_lidar_laser_scan 3d_lidar_laser_scan
  2d_lidar_laser_scan:
    data_type: LaserScan
    sensor_frame: base_link
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: 0.1
    max_obstacle_height: 30.0
    topic: hokuyo_scan
  3d_lidar_laser_scan:
    data_type: LaserScan
    sensor_frame: base_link
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: 0.1
    max_obstacle_height: 30.0
    topic: /rfans/surestar_scan
local_cost_cloud_layer:
  enabled: true
  obstacle_range: 10.5
  raytrace_range: 10.5
  inflation_radius: 1.2
  combination_method: 1
  observation_sources: cost_cloud
  cost_cloud:
    data_type: PointCloud2
    sensor_frame: base_link
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: -.inf
    max_obstacle_height: .inf
    topic: /cost_cloud_process/cost_cloud
global_cost_cloud_layer:
  enabled: false
  obstacle_range: 3.5
  raytrace_range: 3.5
  inflation_radius: 0.4
  combination_method: 0
  observation_sources: cost_cloud
  cost_cloud:
    data_type: PointCloud2
    sensor_frame: base_link
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: -.inf
    max_obstacle_height: .inf
    topic: /cost_cloud_process/cost_cloud
planner_map_layer:
  enabled: true
  use_maximum: true
  subscribe_to_updates: false
  trinary_costmap: true
  map_topic: map_for_costmap
inflation_layer:
  enabled: true
  use_maximum: true
  inflate_unknown: true
  inflation_radius: 0.4
  inflation_radius: 0.5
  cost_scaling_factor: 1.5
  cost_scaling_factor: 0.9
