# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
clearing_rotation_allowed: true
recovery_behavior_enabled: true
recovery_behaviors: 
  - name: local_costmap_clear
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: global_costmap_clear
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: both_costmap_clear
    type: clear_costmap_recovery/ClearCostmapRecovery
local_costmap_clear:
  reset_distance: 0.0
  force_updating: true
  affected_maps: local
  layer_names: 
    - local_obstacles_layer
global_costmap_clear:
  reset_distance: 0.0
  force_updating: true
  affected_maps: global
  layer_names: 
    - global_obstacles_layer
both_costmap_clear:
  reset_distance: 0.0
  force_updating: true
  affected_maps: both
  layer_names: 
    - local_obstacles_layer
    - global_obstacles_layer
move_and_slow:
  reset_distance: 1.0
